database:
  name: テストフォーム
  key: test_form
  directory: db
template:
  form: html/form.html
  thank: html/thank.html
  reply_mail: html/mail.html
  admin_mail: html/admin.html
form:
  input:
    - type: text
      key: full_name
      validation:
        - type: required
        - type: length
          value:
            min: 1
            max: 20
    - type: text
      key: gender
      validation:
        - type: required
        - type: select_one
          value:
            - female
            - male
            - other
    - type: text
      key: hobby
      validation:
        - type: required
        - type: select_any
          value:
            - PC
            - Programming
            - Game
    - type: text
      key: mail_address
      validation:
        - type: email
    - type: text
      key: password
      validation:
        - type: confirmation
        - type: length
          value: 8..84
        - type: only
          value:
            - string
            - number
